services:
  mysql:
    image: mysql:8.4
    container_name: electric-ai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electric_ai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.2
    container_name: electric-ai-redis
    ports:
      - "6379:6379"
